#!/bin/bash

echo "--------------------------------------------------------------------------------"
echo -e "START $(basename $0) $@\n"

if [ -z "$SRCROOT" ]; then
    SRCROOT="$PWD"
fi
if [ -z "$PROJECT_NAME" ]; then
    PROJECT_NAME="$1"
fi

## Config:
#export IDF_TOOLS_PATH="$SRCROOT/env/esp-idf-tools"
#IDF_PATH="$SRCROOT/env/esp-idf"
PROJECT_PBXPROJ_PATH="$SRCROOT/$PROJECT_NAME.xcodeproj/project.pbxproj"

# Read variables:
if [ -z "$PROJECT_NAME" ]; then
    echo "Usage: $0 <PROJECT_NAME>"; exit 1
fi

HEADER_PATHS=(
    "\$(SRCROOT)/env/esp-idf/components/xtensa/include"
    "\$(SRCROOT)/env/esp-idf/components/xtensa/esp32s3/include"
    "\$(SRCROOT)/env/esp-idf/components/newlib/platform_include"
    "\$(SRCROOT)/env/esp-idf/components/freertos/FreeRTOS-Kernel/include"
    "\$(SRCROOT)/env/esp-idf/components/freertos/esp_additions/include/freertos"
    "\$(SRCROOT)/env/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include"
    "\$(SRCROOT)/env/esp-idf/components/freertos/esp_additions/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_hw_support/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_hw_support/include/soc"
    "\$(SRCROOT)/env/esp-idf/components/esp_hw_support/include/soc/esp32s3"
    "\$(SRCROOT)/env/esp-idf/components/esp_hw_support/port/esp32s3"
    "\$(SRCROOT)/env/esp-idf/components/esp_hw_support/port/esp32s3/private_include"
    "\$(SRCROOT)/env/esp-idf/components/heap/include"
    "\$(SRCROOT)/env/esp-idf/components/log/include"
    "\$(SRCROOT)/env/esp-idf/components/soc/include"
    "\$(SRCROOT)/env/esp-idf/components/soc/esp32s3"
    "\$(SRCROOT)/env/esp-idf/components/soc/esp32s3/include"
    "\$(SRCROOT)/env/esp-idf/components/hal/esp32s3/include"
    "\$(SRCROOT)/env/esp-idf/components/hal/include"
    "\$(SRCROOT)/env/esp-idf/components/hal/platform_port/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_rom/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_rom/include/esp32s3"
    "\$(SRCROOT)/env/esp-idf/components/esp_rom/esp32s3"
    "\$(SRCROOT)/env/esp-idf/components/esp_common/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_system/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_system/port/soc"
    "\$(SRCROOT)/env/esp-idf/components/esp_system/port/include/private"
    "\$(SRCROOT)/env/esp-idf/components/lwip/include"
    "\$(SRCROOT)/env/esp-idf/components/lwip/include/apps"
    "\$(SRCROOT)/env/esp-idf/components/lwip/include/apps/sntp"
    "\$(SRCROOT)/env/esp-idf/components/lwip/lwip/src/include"
    "\$(SRCROOT)/env/esp-idf/components/lwip/port/esp32/include"
    "\$(SRCROOT)/env/esp-idf/components/lwip/port/esp32/include/arch"
    "\$(SRCROOT)/env/esp-idf/components/esp_ringbuf/include"
    "\$(SRCROOT)/env/esp-idf/components/efuse/include"
    "\$(SRCROOT)/env/esp-idf/components/efuse/esp32s3/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_timer/include"
    "\$(SRCROOT)/env/esp-idf/components/driver/include"
    "\$(SRCROOT)/env/esp-idf/components/driver/deprecated"
    "\$(SRCROOT)/env/esp-idf/components/driver/esp32s3/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_pm/include"
    "\$(SRCROOT)/env/esp-idf/components/mbedtls/port/include"
    "\$(SRCROOT)/env/esp-idf/components/mbedtls/mbedtls/include"
    "\$(SRCROOT)/env/esp-idf/components/mbedtls/mbedtls/library"
    "\$(SRCROOT)/env/esp-idf/components/mbedtls/esp_crt_bundle/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_app_format/include"
    "\$(SRCROOT)/env/esp-idf/components/bootloader_support/include"
    "\$(SRCROOT)/env/esp-idf/components/bootloader_support/bootloader_flash/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_partition/include"
    "\$(SRCROOT)/env/esp-idf/components/app_update/include"
    "\$(SRCROOT)/env/esp-idf/components/spi_flash/include"
    "\$(SRCROOT)/env/esp-idf/components/pthread/include"
    "\$(SRCROOT)/env/esp-idf/components/app_trace/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_event/include"
    "\$(SRCROOT)/env/esp-idf/components/nvs_flash/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_phy/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_phy/esp32s3/include"
    "\$(SRCROOT)/env/esp-idf/components/vfs/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_netif/include"
    "\$(SRCROOT)/env/esp-idf/components/wpa_supplicant/include"
    "\$(SRCROOT)/env/esp-idf/components/wpa_supplicant/port/include"
    "\$(SRCROOT)/env/esp-idf/components/wpa_supplicant/esp_supplicant/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_wifi/include"
    "\$(SRCROOT)/env/esp-idf/components/unity/include"
    "\$(SRCROOT)/env/esp-idf/components/unity/unity/src"
    "\$(SRCROOT)/env/esp-idf/components/cmock/CMock/src"
    "\$(SRCROOT)/env/esp-idf/components/console"
    "\$(SRCROOT)/env/esp-idf/components/http_parser"
    "\$(SRCROOT)/env/esp-idf/components/esp-tls"
    "\$(SRCROOT)/env/esp-idf/components/esp-tls/esp-tls-crypto"
    "\$(SRCROOT)/env/esp-idf/components/esp_adc/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_adc/interface"
    "\$(SRCROOT)/env/esp-idf/components/esp_adc/esp32s3/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_adc/deprecated/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_eth/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_gdbstub/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_gdbstub/xtensa"
    "\$(SRCROOT)/env/esp-idf/components/esp_gdbstub/esp32s3"
    "\$(SRCROOT)/env/esp-idf/components/esp_hid/include"
    "\$(SRCROOT)/env/esp-idf/components/tcp_transport/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_http_client/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_http_server/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_https_ota/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_lcd/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_lcd/interface"
    "\$(SRCROOT)/env/esp-idf/components/protobuf-c/protobuf-c"
    "\$(SRCROOT)/env/esp-idf/components/protocomm/include/common"
    "\$(SRCROOT)/env/esp-idf/components/protocomm/include/security"
    "\$(SRCROOT)/env/esp-idf/components/protocomm/include/transports"
    "\$(SRCROOT)/env/esp-idf/components/esp_local_ctrl/include"
    "\$(SRCROOT)/env/esp-idf/components/esp_psram/include"
    "\$(SRCROOT)/env/esp-idf/components/espcoredump/include"
    "\$(SRCROOT)/env/esp-idf/components/espcoredump/include/port/xtensa"
    "\$(SRCROOT)/env/esp-idf/components/wear_levelling/include"
    "\$(SRCROOT)/env/esp-idf/components/sdmmc/include"
    "\$(SRCROOT)/env/esp-idf/components/fatfs/diskio"
    "\$(SRCROOT)/env/esp-idf/components/fatfs/vfs"
    "\$(SRCROOT)/env/esp-idf/components/fatfs/src"
    "\$(SRCROOT)/env/esp-idf/components/idf_test/include"
    "\$(SRCROOT)/env/esp-idf/components/idf_test/include/esp32s3"
    "\$(SRCROOT)/env/esp-idf/components/ieee802154/include"
    "\$(SRCROOT)/env/esp-idf/components/json/cJSON"
    "\$(SRCROOT)/env/esp-idf/components/mqtt/esp-mqtt/include"
    "\$(SRCROOT)/env/esp-idf/components/perfmon/include"
    "\$(SRCROOT)/env/esp-idf/components/spiffs/include"
    "\$(SRCROOT)/env/esp-idf/components/touch_element/include"
    "\$(SRCROOT)/env/esp-idf/components/ulp/ulp_common/include"
    "\$(SRCROOT)/env/esp-idf/components/ulp/ulp_common/include/esp32s3"
    "\$(SRCROOT)/env/esp-idf/components/usb/include"
    "\$(SRCROOT)/env/esp-idf/components/wifi_provisioning/include"
)

paths=$(printf ',"%s"' "${HEADER_PATHS[@]}")
paths=${paths:2}
awk -v path="$PROJECT_PBXPROJ_PATH" -v paths="$paths" '{ file=file $0 "\n" } END { gsub(/HEADER_SEARCH_PATHS = [^;]*;/, "HEADER_SEARCH_PATHS = (\"" paths ");", file); print file > path }' "$PROJECT_PBXPROJ_PATH"

echo -e "\nDONE $(basename $0) $@"
echo "--------------------------------------------------------------------------------"
